environment: ZT004

execution:
    timeout: 20
    pageLoadTimeout: 30
    pollingInterval: 250
    threadCount: 4

selenium:
    grid: false
    debug: false
    headless: false
    maximizeWindow: true
    windowWidth: 1920
    windowHeight: 1080

grid:
    hubUrl: "http://localhost:4444/wd/hub"